name: 'ARM GCC build'
description: 'Building arm-gcc projects'
branding:
  color: blue
  icon: microchip
inputs:
   command:
     description: 'Command'
     required: true
     default: arm-none-eabi-gcc --version
runs:
  using: 'docker'
  image: 'docker://sergeyladanov/arm-gcc:12.3.rel1-v1'
  args:
     - ${{ inputs.command }}
 
