name: 'ARM GCC build'
description: 'Building arm projects'
inputs:
   command:
     description: 'Command'
     required: true
     default: arm-none-eabi-gcc --version
runs:
  using: 'docker'
  image: 'Action.Dockerfile'
  args:
    - /bin/sh
    - -c
    - ${{ inputs.command }}
 
